name: 'IOS Appium Workflow Action'
description: 'Custom GitHub Action to run Appium tests with Maven.'
inputs:
  java_version:
    description: 'The version of Java to install.'
    required: false
    default: '22'

  node_version:
    description: 'The version of NodeJS to install.'
    required: false
    default: '21'

  test_name:
    description: 'The name of the test suite.'
    required: true
  
  env_file_path:
    description: 'The path of the environment configuration'
    required: true

  scripts:
    description: 'The maven commands to execute the test.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java_version }}

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}

    - name: Check bash scripts
      run: |
        chmod +x ./automated_ios_test_setup.sh
        ./automated_ios_test_setup.sh "Iphone 15" 17-5
        DEVICE_UDID=$(xcrun simctl list devices | grep "(Booted)" | awk -F '[()]' '{print $2}' | head -n1)
        echo "DEVICE_UDID=$DEVICE_UDID" >> $GITHUB_ENV
      shell: bash

    - name: Install dependencies
      run: |
        mvn install -DskipTests
      shell: bash

    - name: Run Tests
      run: |
        echo "iosSimulatorUdid=$DEVICE_UDID" > ${{ inputs.env_file_path }}
        eval "${{ inputs.scripts }}" | tee terminal_log.txt
      shell: bash

    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Test Reports - ${{ inputs.test_name }}
        path: |
          **/BufferLog.log
          **/ExtentReport.html

    - name: Check for SessionNotCreatedException
      id: check_error
      run: |
        if grep -q "org.openqa.selenium.SessionNotCreatedException:" terminal_log.txt; then
          echo "ERROR_FOUND=true" >> $GITHUB_ENV
        else
          echo "ERROR_FOUND=false" >> $GITHUB_ENV
        fi
      shell: bash
  
    - name: Upload Appium Logs
      if: env.ERROR_FOUND == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: Appium Logs - ${{ inputs.test_name }}
        path: appium_log.txt
